### PR TITLE
Fix various bugs

### PR DESCRIPTION
**Pull request by Alwinfy**

### CODE REVIEW

**Comment by 2767mr** [comment]
Only added .replace('\`', '') to box args.
Also changed `EXPLOSION!` to `EKUSUPUROSION!`.

**Comment by 2767mr** [comment]
Closed as a simple replace('\`', '') will not remove all ` ` `

**Comment by ac2pic** [comment]
Input cleaning should be it's own utility.

**Comment by cloudrac3r** [comment]
.replace(/`/g, "`​")

This will add a zero-width space after the `, thus preventing them from joining together and closing the code block.

May I also suggest decreasing the maximum character limit down to 40?

**Comment by ac2pic** [comment]
1. I think you mean .replace(/`/g, ""). 
2. Sure.

**Comment by cloudrac3r** [comment]
No, I meant what I wrote.

**Comment by ac2pic** [comment]
Nevermind, saw the empty space.

**Comment by 2767mr** [comment]
Source code has not changed so issues mentioned above are still valid. Closing

**Pull request closed without merging**
